### PR TITLE
more hashmap benchmarks

### PR DESCRIPTION
**Pull request by Sahnvour**
See https://martin.ankerl.com/2019/04/01/hashmap-benchmarks-01-overview/ for more details on the benchmarks themselves.

These are quite long (easily one or two minutes) compared to the existing hashmap benchmarks.
I'm not sure how to contribute them, each one being a separate benchmark or all at once, as they already do enough work by themselves without needing to be run multiple times.
I'm also unsure what is intended by the main/baseline dichotomy. Should I replace the baseline by main before doing this change ?

Also they still have debug output that's handy when running them all at once. Is it a problem ?

### CODE REVIEW

**Comment by andrewrk** [comment]
Each one should be a new benchmark, leaving the existing one unmodified. Each benchmark does not do any timing or printing to stdio in the run() function; that is managed by the harness. Maybe we can start with just one new benchmark for now and see how it goes. This repository is not able to handle benchmarks that do their own bookkeeping; that is out of scope.

The main/baseline dichotomy is to make this data correct over time as the hardware that it runs on changes. For every benchmark, it runs the fixed baseline followed by the commit in question, and then it is recommended to look at the relative differences when charting the data. This is why the graphs are in terms of percent relative to the baseline. Explained more in the [Strategy section of the readme](https://github.com/ziglang/gotta-go-fast#strategy) If the baseline commit is capable of running the exact same code as master branch, then you can use the same files for baseline and main. However if any breaking changes happen to the std lib or language then we would have to split into baseline/main to keep the benchmark alive. We can also retire benchmarks if the baseline they are using gets too old.

Ideally each benchmark would take less than a minute to run, because we want to potentially run a large number of benchmarks per commit and multiplying > 1 minute by 100s of benchmarks quickly gets into the hours. It's OK, but we have finite resources, and should not waste them when a shorter duration would give basically the same amount of data. Remember that we are comparing against baseline, and we can observe differences even on a test case that runs very quickly.

**Comment by Sahnvour** [comment]
Thanks for the explanation. I updated the code with split up benchmarks, and reduced their individual duration a bit so that they don't take forever.
However I didn't try with the main runner, just launched them one by one during my tests.

**Comment by andrewrk** [comment]
Thanks! I'll take another look. Don't worry-   if there's any problem with it, I'll fiddle with it to get it working before merging.

**Comment by andrewrk** [comment]
So here's why we need a baseline.zig file for insert-10M-int for example:

```
Running 'insert-10M-int' for 0d31877444bf6c21307dfd3c412f9673dfd8acab, allocator=libc, baseline...
./insert-10M-int.zig:25:8: error: no member named 'clearRetainingCapacity' in struct 'std.hash_map.HashMap(i32,i32,std.hash_map.getAutoHashFn(i32).hash,std.hash_map.getAutoEqlFn(i32).eql)'
    map.clearRetainingCapacity();
       ^
```

we didn't have that function in `feade9ef0010b1b47d7216e786ed964d09612c2b`, so the choices would be either to establish a newer baseline for this benchmark (totally fine) or to make a separate baseline.zig file that works with that older commit. I'll go with the latter for now because I'm lazy.

**Pull request merged**
