### PR TITLE
Fix single benchmark command example

### PR DESCRIPTION
**Pull request by Sahnvour**
`main.zig` does it, and it's very much needed :)

### CODE REVIEW

**Comment by andrewrk** [comment]
why is that needed?

**Comment by Sahnvour** [comment]
Nevermind, I was persuaded I needed it at one point but apparently that was a mistake on my end.

**Comment by Sahnvour** [comment]
Encountered again why I thought cache off is needed :

```bash
$ zig run --main-pkg-path . --pkg-begin app benchmarks/rand/main.zig --pkg-end --release-fast -lc bench.zig -- C:\dev\install\zig
Unable to open C:\dev\Zig\gotta-go-fast\benchmarks\std-hash-map\main.zig
: file not found

$ zig run --main-pkg-path . --pkg-begin app benchmarks/rand/main.zig --pkg-end --release-fast -lc bench.zig --cache off -- C:\dev\install\zig
{"samples_taken":15,"wall_time":{"median":703211300,"mean":703258923,"min":703119600,"max":703518900},"utime":{"median":0,"mean":0,"min":0,"max":0},"stime":{"median":0,"mean":0,"min":0,"max":0},"maxrss":0}
```

**Comment by andrewrk** [comment]
not sure why --cache off is relevant here. Is there a newline in the file path?

**Comment by Sahnvour** [comment]
There's no new line, and until --cache off is used (as in the second command), it appears the build executable is not remade and then tries to compile an old file that doesn't exist anymore (just switched branches). Sorry, that wasn't very explicit.

It's probably a silly error but I just don't see it.

**Comment by andrewrk** [comment]
Hmmmm this potentially looks like package arguments not being properly added to the cache hash. That's a big deal, we have to fix it, we can't just suggest to turn the cache off!

**Pull request closed without merging**
